# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  # Link to your container registry. You will launch it in Yandex Cloud.
  repository: cr.yandex/crpgtflfhr7osd5rl7gv/dds
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

containerPort: 5000

config:
  KAFKA_HOST: 'rc1a-phml9v7algis3bof.mdb.yandexcloud.net'
  KAFKA_PORT: '9091'
  KAFKA_CONSUMER_USERNAME: 'producer_consumer'
  KAFKA_CONSUMER_PASSWORD: 'Das714239'
  KAFKA_CONSUMER_GROUP: 'demo'
  KAFKA_SOURCE_TOPIC: "stg-service-orders"
  KAFKA_DESTINATION_TOPIC: "stg-service-orders"

  PG_WAREHOUSE_HOST: 'rc1b-4nsueuw15pcp4amf.mdb.yandexcloud.net'
  PG_WAREHOUSE_PORT: '6432'
  PG_WAREHOUSE_DBNAME: 'sprint9dwh'
  PG_WAREHOUSE_USER: 'db_user'
  PG_WAREHOUSE_PASSWORD: 'Das714239'

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
